background            #313132
foreground            #8dffd5

# black
color0  #313132
color8  #84838a

# red
color1  #d68679
color9  #ffa998

# green
color2  #47ae83
color10 #63d89f

# yellow
color3  #46b287
color11 #61dca3

# blue
color4  #849be3
color12 #a8beff

# magenta
color5  #c086c6
color13 #eca6f8

#cyan
color6  #6ca48f
color14 #8bccb0

#white
color7  #8dffd5
color15 #7effcd


